name: CI/CD — NexaCloud API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  lint:
    uses: ./.github/workflows/lint.yml
  test:
    needs: lint
    uses: ./.github/workflows/test.yml
  staging:
    needs: test
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "staging"
  production:
    needs: staging
    secrets: inherit
    uses: ./.github/workflows/deploy.yml
    with:
      environment: "production"
