name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      environment:
        description: "Environnement sur lequel déployer"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

jobs:
  deploy-staging:
    if: ${{ inputs.environment == 'staging' }}
    runs-on: ubuntu-latest
    environment: staging          # utilise l'environnement staging

    steps:
      - name: Déployer en staging
        run: echo "Déploiement en staging..."

  deploy-production:
    if: ${{ inputs.environment == 'production' }}
    runs-on: ubuntu-latest
    environment: production
    needs: deploy-staging

    steps:
      - name: Déployer en production
        run: echo "Déploiement en production !"