name: Unit Tests
on:
    workflow_call:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v6

      # Mettre en cache les dépendances pip (accélère les builds suivants)
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('ressources/requirements.txt') }}

      - name: Installer les dépendances
        run: pip install -r ressources/requirements.txt

      # Ajouter la couverture de tests et publier le rapport
      - name: Tests avec couverture
        run: pytest ressources/ -v --cov=ressources --cov-report=term --cov-report=html:htmlcov/

      - name: Upload du rapport
        uses: actions/upload-artifact@v4
        with:
          name: rapport-couverture
          path: htmlcov/
